//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AZERS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Djelatnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Djelatnik()
        {
            this.ProjektDjelatniks = new HashSet<ProjektDjelatnik>();
            this.Satnicas = new HashSet<Satnica>();
        }
    
        public int IDDjelatnik { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Email { get; set; }
        public System.DateTime DatumZaposlenja { get; set; }
        public string Lozinka { get; set; }
        public int TipDjelatnikaID { get; set; }
        public Nullable<int> TimID { get; set; }
        public string Aktivan { get; set; }
        public string Jezik { get; set; }
    
        public virtual Tim Tim { get; set; }
        public virtual TipDjelatnika TipDjelatnika { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjektDjelatnik> ProjektDjelatniks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satnica> Satnicas { get; set; }
    }
}
