//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AZERS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satnica
    {
        public int IDSatnica { get; set; }
        public Nullable<System.TimeSpan> BrojZabiljezenihSati { get; set; }
        public Nullable<System.TimeSpan> BrojRedovnihSati { get; set; }
        public Nullable<System.TimeSpan> BrojPrekovremenihSati { get; set; }
        public Nullable<System.TimeSpan> StartVrijeme { get; set; }
        public Nullable<System.TimeSpan> StopVrijeme { get; set; }
        public Nullable<System.TimeSpan> VrijemeSlanjaSatnice { get; set; }
        public System.DateTime DatumSatnice { get; set; }
        public Nullable<System.DateTime> DatumSlanjaSatnice { get; set; }
        public string StatusSatnice { get; set; }
        public int ProjektID { get; set; }
        public int KlijentID { get; set; }
        public int DjelatnikID { get; set; }
        public int TimID { get; set; }
    
        public virtual Djelatnik Djelatnik { get; set; }
        public virtual Klijent Klijent { get; set; }
        public virtual Projekt Projekt { get; set; }
        public virtual Tim Tim { get; set; }
    }
}
